-- Table: barn

-- DROP TABLE barn;

CREATE TABLE IF NOT EXISTS barn
(
    barn_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    person_id varchar(50),
    navn varchar(255),
    foedselsdato date,
    foedselsaar integer,
    doedsdato date,
    aktiv boolean DEFAULT true NOT NULL,
    bruk_fra timestamp DEFAULT now() NOT NULL,
    bruk_til timestamp,
    opprettet_av varchar(255),
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    CONSTRAINT barn_pkey PRIMARY KEY (barn_id),
    CONSTRAINT grunnlagspakke_barn_fkey FOREIGN KEY (grunnlagspakke_id)
        REFERENCES grunnlagspakke (grunnlagspakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (barn_id, grunnlagspakke_id)
)

    TABLESPACE pg_default;
