-- Table: grunnlagspakke

-- DROP TABLE grunnlagspakke;

CREATE TABLE IF NOT EXISTS grunnlagspakke
(
    grunnlagspakke_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    opprettet_av varchar(255) NOT NULL,
    opprettet_timestamp timestamp DEFAULT now() NOT NULL,
    endret_timestamp timestamp,
    gyldig_til date,
    formaal varchar(50) not null,
    CONSTRAINT grunnlagspakke_pkey PRIMARY KEY (grunnlagspakke_id)
)

    TABLESPACE pg_default;