-- Table: barnetillegg

-- DROP TABLE barnetillegg;

CREATE TABLE IF NOT EXISTS barnetillegg
(
    barnetillegg_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    part_person_id varchar(50) NOT NULL,
    barn_person_id varchar(50) NOT NULL,
    barnetillegg_type varchar(255) NOT NULL,
    periode_fra date NOT NULL,
    periode_til date,
    aktiv boolean DEFAULT true NOT NULL,
    bruk_fra timestamp DEFAULT now() NOT NULL,
    bruk_til timestamp,
    belop_brutto float NOT NULL,
    barn_type varchar(255) NOT NULL,
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    CONSTRAINT barnetillegg_pkey PRIMARY KEY (barnetillegg_id),
    CONSTRAINT grunnlagspakke_fkey FOREIGN KEY (grunnlagspakke_id)
        REFERENCES grunnlagspakke (grunnlagspakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (barnetillegg_id, grunnlagspakke_id)
)

    TABLESPACE pg_default;