-- Table: kontantstotte

-- DROP TABLE kontantstotte

CREATE TABLE IF NOT EXISTS kontantstotte
(
    kontantstotte_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    part_person_id varchar(50) not null,
    barn_person_id varchar(50) NOT NULL,
    periode_fra date NOT NULL,
    periode_til date,
    aktiv boolean DEFAULT true NOT NULL,
    bruk_fra timestamp DEFAULT now() NOT NULL,
    bruk_til timestamp,
    belop integer NOT NULL,
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    CONSTRAINT kontantstotte_pkey PRIMARY KEY (kontantstotte_id),
    CONSTRAINT grunnlagspakke_kontantstotte_fkey FOREIGN KEY (grunnlagspakke_id)
        REFERENCES grunnlagspakke (grunnlagspakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (kontantstotte_id, grunnlagspakke_id)
)
    TABLESPACE pg_default;