-- Table: skattegrunnlagspost
--
-- DROP TABLE inntektspost_skatt;

CREATE TABLE IF NOT EXISTS skattegrunnlagspost
(
    skattegrunnlagspost_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    skattegrunnlag_id integer NOT NULL,
    skattegrunnlag_type varchar(255) NOT NULL,
    inntekt_type varchar(255) NOT NULL,
    belop float NOT NULL,
    CONSTRAINT skattegrunnlagspost_skatt_pkey PRIMARY KEY (skattegrunnlagspost_id),
    CONSTRAINT skattegrunnlag_fkey FOREIGN KEY (skattegrunnlag_id)
        REFERENCES skattegrunnlag (skattegrunnlag_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (skattegrunnlag_id, skattegrunnlag_type, inntekt_type)
)

    TABLESPACE pg_default;
