-- Table: husstand

-- DROP TABLE husstand;

CREATE TABLE IF NOT EXISTS husstand
(
    husstand_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    person_id varchar(50),
    periode_fra date,
    periode_til date,
    adressenavn varchar(255),
    husnummer varchar(255),
    husbokstav varchar(255),
    bruksenhetsnummer varchar(255),
    postnummer varchar(255),
    bydelsnummer varchar(255),
    kommunenummer varchar(255),
    matrikkelId bigint,
    landkode varchar(50),
    aktiv boolean DEFAULT true NOT NULL,
    bruk_fra timestamp DEFAULT now() NOT NULL,
    bruk_til timestamp,
    opprettet_av varchar(255),
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    CONSTRAINT husstand_pkey PRIMARY KEY (husstand_id),
    CONSTRAINT grunnlagspakke_husstand_fkey FOREIGN KEY (grunnlagspakke_id)
        REFERENCES grunnlagspakke (grunnlagspakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (husstand_id, grunnlagspakke_id)
)

    TABLESPACE pg_default;

